# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SkuEventMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SkuEventMessage.proto',
  package='event',
  serialized_pb=_b('\n\x15SkuEventMessage.proto\x12\x05\x65vent\"\x92\x01\n\x0fSkuEventMessage\x12\x12\n\nrequest_id\x18\x01 \x02(\t\x12\x13\n\x0b\x65vent_label\x18\x02 \x02(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x06\x12\x12\n\ncreated_by\x18\x04 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x11.event.SkuMessage\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"\xaa\x02\n\nSkuMessage\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0c\n\x04\x63ode\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x15\n\rspecification\x18\x04 \x02(\t\x12\x0b\n\x03uom\x18\x05 \x02(\t\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x15\n\rhandling_list\x18\x07 \x01(\t\x12\x19\n\x04size\x18\x08 \x02(\x0b\x32\x0b.event.Size\x12\x1d\n\x06\x64\x65tail\x18\t \x02(\x0b\x32\r.event.Detail\x12\x10\n\x08\x63\x61tegory\x18\n \x02(\t\x12\x0e\n\x06status\x18\x0b \x02(\x08\x12\x12\n\ncreated_at\x18\x0c \x01(\x06\x12\x12\n\ncreated_by\x18\r \x01(\t\x12\x12\n\nupdated_at\x18\x0e \x01(\x06\x12\x12\n\nupdated_by\x18\x0f \x01(\t\"r\n\x04Size\x12!\n\x05inner\x18\x01 \x02(\x0b\x32\x12.event.SizePattern\x12!\n\x05outer\x18\x02 \x02(\x0b\x32\x12.event.SizePattern\x12$\n\x08packages\x18\x03 \x02(\x0b\x32\x12.event.SizePattern\"c\n\x0bSizePattern\x12\x0e\n\x06length\x18\x01 \x02(\r\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\x0e\n\x06weight\x18\x04 \x02(\r\x12\x15\n\rsize_category\x18\x05 \x02(\t\"&\n\x06\x44\x65tail\x12\x1c\n\x06images\x18\x01 \x03(\x0b\x32\x0c.event.Image\"\x14\n\x05Image\x12\x0b\n\x03url\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SKUEVENTMESSAGE = _descriptor.Descriptor(
  name='SkuEventMessage',
  full_name='event.SkuEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='event.SkuEventMessage.request_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_label', full_name='event.SkuEventMessage.event_label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='event.SkuEventMessage.created_at', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='event.SkuEventMessage.created_by', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='event.SkuEventMessage.data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='event.SkuEventMessage.error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=179,
)


_SKUMESSAGE = _descriptor.Descriptor(
  name='SkuMessage',
  full_name='event.SkuMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='event.SkuMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='event.SkuMessage.code', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='event.SkuMessage.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specification', full_name='event.SkuMessage.specification', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uom', full_name='event.SkuMessage.uom', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='event.SkuMessage.type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='handling_list', full_name='event.SkuMessage.handling_list', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='event.SkuMessage.size', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detail', full_name='event.SkuMessage.detail', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='category', full_name='event.SkuMessage.category', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='event.SkuMessage.status', index=10,
      number=11, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='event.SkuMessage.created_at', index=11,
      number=12, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='event.SkuMessage.created_by', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='event.SkuMessage.updated_at', index=13,
      number=14, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated_by', full_name='event.SkuMessage.updated_by', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=480,
)


_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='event.Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inner', full_name='event.Size.inner', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outer', full_name='event.Size.outer', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='event.Size.packages', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=596,
)


_SIZEPATTERN = _descriptor.Descriptor(
  name='SizePattern',
  full_name='event.SizePattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='event.SizePattern.length', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='event.SizePattern.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='event.SizePattern.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='event.SizePattern.weight', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size_category', full_name='event.SizePattern.size_category', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=697,
)


_DETAIL = _descriptor.Descriptor(
  name='Detail',
  full_name='event.Detail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='event.Detail.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=737,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='event.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='event.Image.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=759,
)

_SKUEVENTMESSAGE.fields_by_name['data'].message_type = _SKUMESSAGE
_SKUMESSAGE.fields_by_name['size'].message_type = _SIZE
_SKUMESSAGE.fields_by_name['detail'].message_type = _DETAIL
_SIZE.fields_by_name['inner'].message_type = _SIZEPATTERN
_SIZE.fields_by_name['outer'].message_type = _SIZEPATTERN
_SIZE.fields_by_name['packages'].message_type = _SIZEPATTERN
_DETAIL.fields_by_name['images'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['SkuEventMessage'] = _SKUEVENTMESSAGE
DESCRIPTOR.message_types_by_name['SkuMessage'] = _SKUMESSAGE
DESCRIPTOR.message_types_by_name['Size'] = _SIZE
DESCRIPTOR.message_types_by_name['SizePattern'] = _SIZEPATTERN
DESCRIPTOR.message_types_by_name['Detail'] = _DETAIL
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE

SkuEventMessage = _reflection.GeneratedProtocolMessageType('SkuEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _SKUEVENTMESSAGE,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.SkuEventMessage)
  ))
_sym_db.RegisterMessage(SkuEventMessage)

SkuMessage = _reflection.GeneratedProtocolMessageType('SkuMessage', (_message.Message,), dict(
  DESCRIPTOR = _SKUMESSAGE,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.SkuMessage)
  ))
_sym_db.RegisterMessage(SkuMessage)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), dict(
  DESCRIPTOR = _SIZE,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.Size)
  ))
_sym_db.RegisterMessage(Size)

SizePattern = _reflection.GeneratedProtocolMessageType('SizePattern', (_message.Message,), dict(
  DESCRIPTOR = _SIZEPATTERN,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.SizePattern)
  ))
_sym_db.RegisterMessage(SizePattern)

Detail = _reflection.GeneratedProtocolMessageType('Detail', (_message.Message,), dict(
  DESCRIPTOR = _DETAIL,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.Detail)
  ))
_sym_db.RegisterMessage(Detail)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'SkuEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:event.Image)
  ))
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
